// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTwaHhYt0SCyIpQtxhtMetBIyEXnKdrH4',
    appId: '1:167361576773:web:2c4de95051ce7b0db2482c',
    messagingSenderId: '167361576773',
    projectId: 'climora-musical-app1',
    authDomain: 'climora-musical-app1.firebaseapp.com',
    storageBucket: 'climora-musical-app1.firebasestorage.app',
    measurementId: 'G-3F7VMLK9B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnR3FqjgXwj5BJZd3nS2Ef2WhtZipTj34',
    appId: '1:167361576773:android:2922733fe177bddbb2482c',
    messagingSenderId: '167361576773',
    projectId: 'climora-musical-app1',
    storageBucket: 'climora-musical-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXGFc7XLM6UNC184NhrB2QcfGSJnbAmo',
    appId: '1:167361576773:ios:41a480b1e162c54db2482c',
    messagingSenderId: '167361576773',
    projectId: 'climora-musical-app1',
    storageBucket: 'climora-musical-app1.firebasestorage.app',
    iosBundleId: 'com.example.climora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXGFc7XLM6UNC184NhrB2QcfGSJnbAmo',
    appId: '1:167361576773:ios:41a480b1e162c54db2482c',
    messagingSenderId: '167361576773',
    projectId: 'climora-musical-app1',
    storageBucket: 'climora-musical-app1.firebasestorage.app',
    iosBundleId: 'com.example.climora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTwaHhYt0SCyIpQtxhtMetBIyEXnKdrH4',
    appId: '1:167361576773:web:d225aaa61ebeb1b1b2482c',
    messagingSenderId: '167361576773',
    projectId: 'climora-musical-app1',
    authDomain: 'climora-musical-app1.firebaseapp.com',
    storageBucket: 'climora-musical-app1.firebasestorage.app',
    measurementId: 'G-LDQMPFMFK0',
  );
}
